{{- range $app := .Values.apps }}
# Section {{ $app.name }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "$app.name is required" $app.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required ".Values.project.metadata.name is required" $.Values.project.metadata.name }}

  destination:
    namespace: {{ required "$app.namespace is required" $app.namespace }}
    server: {{ $app.destination | default "https://kubernetes.default.svc" | quote }}

  source:
    repoURL: {{ required ".Values.repository.url is required" $.Values.repository.url }}
    targetRevision: {{ required ".Values.repository.revision is required" $.Values.repository.revision }}
    {{- if $app.releaseName }}
    path: {{ printf "%s/%s/%s" (required "$app.repository.path" $app.repository.path) (required ".Values.global.region" $.Values.global.region) (required ".Values.global.environment" $.Values.global.environment) }}
    helm:
      releaseName: {{ $app.releaseName }}
      valueFiles:
      {{- range $i, $values := $app.repository.values }}
      - {{ $values }}
      {{- end }}
      {{- if ((($app).repository).files) }}
      fileParameters:
{{- $app.repository.files | toYaml | nindent 6 }}
      {{- end }}
    {{- else }}
    path: {{ required "$app.repository.path is required" $app.repository.path }}
    {{- end }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
     managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false
---
{{- end }}
