{{- if .Values.applications -}}
{{- range $name, $application := .Values.applications -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required ".Values.project.metadata.name is required" $.Values.project.metadata.name }}

  destination:
    namespace: {{ $application.metadata.namespace }}
    server: {{ $application.metadata.destination }}

  source:
    repoURL: {{ $application.source.repoURL }}
    targetRevision: {{ $application.source.targetRevision }}
    path: {{ $application.source.path }}

    {{ if $application.source.helm }}
    helm:
      releaseName: {{ $name }}
      valueFiles:
      {{- range $i, $values := $application.source.helm.values }}
        - {{ $values }}
      {{- end }}
    {{ end }}

  syncPolicy:
  {{ $application.syncPolicy | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
