applications:
  service:
    metadata:
      namespace: default
      destination: https://kubernetes.default.svc
    source:
      path: /
      repoURL: git@github.com:cloud-tek/repository.git
      targetRevision: HEAD

      helm:
        values:
        - values.yaml

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
