apiVersion: v1
kind: Secret
metadata:
  name: argocd-avp-configuration
  namespace: argocd
type: Opaque
stringData:
  AVP_TYPE: {{ .Values.argocd.vaultProvider.type | quote }}
  OP_CONNECT_TOKEN: {{ .Values.onepassword.connect.token | quote }}
  OP_CONNECT_HOST: {{ .Values.onepassword.connect.host | quote }}
