{{- if .Values.cloudflare -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ printf "%s.cluster-issuer-key" .Release.Name }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ required ".Values.cloudflare.email is required" .Values.cloudflare.email | quote }}
          apiTokenSecretRef:
            name: {{ printf "%s.cloudflare-token" .Release.Name }}
            key: token
{{- end -}}
