{{- if .Values.cloudflare -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ required ".Values.certificate.name is required" .Values.certificate.name | quote }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ printf "%s.cluster-issuer-key" .Values.certificate.name }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ required ".Values.cloudflare.email is required" .Values.cloudflare.email | quote }}
          apiTokenSecretRef:
            name: {{ printf "%s.cloudflare-token" .Values.certificate.name }}
            key: token
{{- end -}}
