{{- if .Values.cloudflare }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.cloudflare-token" .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  token: {{ required ".Values.cloudflare.token must be provided" .Values.cloudflare.token | quote }}
{{- end -}}
