apiVersion: v2
name: cert-manager-cluster-issuer
description: HELM chart containig a seed ClusterIssuer for cert-manager
type: application
icon: https://avatars.githubusercontent.com/u/35167581?s=400&u=ca5fdf8da213a9ab3edd83813b5f3491dea70f6c&v=4
version: 0.2.1
appVersion: 0.1.0
