name: ci

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
    - ".github/workflows/**"
    - "opa/**"
    - "service/**"
    - "argocd-project/**"
    - "README.md"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
    - ".github/workflows/**"
    - "opa/**"
    - "service/**"
    - "argocd-project/**"
    - "README.md"

  workflow_dispatch:
    inputs: {}

jobs:
  helm:
    uses: ./.github/workflows/helm.yml
    with:
      version: v3.10.3
      platform: linux-amd64
      charts: |
        [
          {
            "id": "service"
          },
          {
            "id": "argocd-project"
          },
          {
            "id": "argocd-vault-provider"
          }
        ]
  kubeconform:
    uses: ./.github/workflows/kubeconform.yml
    needs:
    - helm
    with:
      charts: |
        [
          {
            "id": "service"
          },
          {
            "id": "argocd-vault-provider"
          }
        ]
  opa:
    uses: ./.github/workflows/opa.yml
    needs:
    - helm
    with:
      charts: |
        [
          {
            "id": "service"
          }
        ]

  ghcr:
    uses: ./.github/workflows/ghcr.yml
    needs:
    - helm
    - kubeconform
    - opa
    with:
      version: v3.10.3
      platform: linux-amd64
      charts: |
        [
          {
            "id": "service"
          },
          {
            "id": "argocd-project"
          },
          {
            "id": "argocd-vault-provider"
          }
        ]
    secrets:
      GHCR_Token: ${{ secrets.GHCR_Token }}
