name: "opa"

on:
  workflow_call:
    inputs:
      charts:
        description: "list of charts to lint"
        type: string
        required: true

jobs:
  opa:
    name: opa
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(inputs.charts) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
